#!/bin/bash

declare -A sup
declare -A cli
declare -a id
declare -a error
declare -a errorG

grep "BASED" $1 > supervisor_grep
grep "SECRET" $2 > client_grep

i=0
j=0
somma=0
sommaG=0
corrette=0

IFS=' '

while IFS=' ' read -r f1 f2 f3 f4 f5 f6 f7 f8
do
	sup[${f5}]=$f3
	i=$(($i+1))
done < supervisor_grep 

while IFS=' ' read -r c1 c2 c3 c4
do
	cli[$c2]=$c4
	id[$j]=$c2
	j=$(($j+1))
done < client_grep

stime=$j
soglia=25
k=0

for(( i = 0; i < $stime; i++ )); do
	err=$((sup[${id[$i]}]-cli[${id[$i]}]))
	err=${err#-}

	echo "--------------------------------------------------------------"
	echo "$id : stimato : ${sup[${id[$i]}]} effettivo: ${cli[${id[$i]}]}"
	

	errorG[$i]=$err
	
	if [[ $err -le $soglia ]]; then
		error[$k]=$err
		k=$(($k+1))
		corrette=$(($corrette+1))
	fi
done

printf "\n-------------------------statistiche--------------------------\n\n"

for (( i = 0; i < $k; i++ )); do
	somma=$(($somma+${error[$i]}))
done
for (( i = 0; i < $k; i++ )); do
	sommaG=$(($sommaG+${errorG[$i]}))
done

percent=$(($corrette*100/$stime))

echo " Numero stime corrette entro 25msec di $stime clients è: $corrette"
echo " Percentuale stime corrette: $percent %"
echo " Errore medio nella stima di secret entro 25msec: $somma / $corrette"
echo " Errore medio globale nella stima di secret : $sommaG / $stime"

printf "\n-------------------------statistiche--------------------------\n"